spring:
  profiles:
    active: prod
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
#      url: jdbc:mysql://127.0.0.1:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    encoding: utf-8
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host: 127.0.0.1        # Redis服务器地址
    port: 6379             # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500     # 连接池中的最大空闲连接
        min-idle: 50      # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath*:mapper/**/*.xml
    type-aliases-package: com.clw.entity
    configuration:
      map-underscore-to-camel-case: true

# 日志文件
logging:
  file: myapp.log
  max-history: 1
  max-size: 10MB
  path: /
# 邮箱设置
mail:
  host: smtp.163.com
  username: 13535240192@163.com
  password:
  properties:
      mail:
          smtp:
              auth: true
              timeout: 25000
